#  @BikeService_HostAddress = http://localhost:5146
#  @StationService_HostAddress = http://localhost:5139

# @BikeAtStationService_HostAddress = http://localhost:5226

@BikeService_HostAddress = http://localhost:5001
@StationService_HostAddress = http://localhost:5002
@BikeAtStationService_HostAddress = http://localhost:5003

###
GET {{BikeService_HostAddress}}/bike/
Accept: application/json

###
GET {{StationService_HostAddress}}/station/
Accept: application/json

###
POST {{BikeService_HostAddress}}/bike/
Accept: application/json
Content-Type: application/json

{
  "model": "Trek FX 3 Disc123",
  "color": "Blac3k",
  "lastServiceDate": "2024-08-10"
}

###
DELETE {{BikeService_HostAddress}}/bike/7
Accept: application/json
Content-Type: application/json


###
POST {{StationService_HostAddress}}/station/
Accept: application/json
Content-Type: application/json

{
  "code": "ST1236",
  "location": "Warszawa",
  "capacity": 26
}

###
POST {{BikeAtStationService_HostAddress}}/bikeAtStation
Accept: application/json
Content-Type: application/json

{
  "externalBikeId": "2563bc65-a430-4b59-a2ca-16e6d2e0e595",
  "externalStationId": "a2bcc144-d7f8-4976-a13a-79effc348c4e"
}