# @BikeService_HostAddress = http://localhost:5146
# @StationService_HostAddress = http://localhost:5139

@BikeService_HostAddress = http://localhost:5001
@StationService_HostAddress = http://localhost:5002

###
GET {{BikeService_HostAddress}}/bike/
Accept: application/json

###
GET {{StationService_HostAddress}}/station/
Accept: application/json

###
POST {{BikeService_HostAddress}}/bike/
Accept: application/json
Content-Type: application/json

{
  "model": "Trek FX 3 Disc123",
  "color": "Blac3k",
  "lastServiceDate": "2024-08-10"
}

