// <auto-generated />
using System;
using BikeRental.StationService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BikeRental.StationService.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250911231036_AddBike")]
    partial class AddBike
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("BikeRental.StationService.Domain.Entities.BikeAtStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("BikeExternalId")
                        .HasColumnType("TEXT");

                    b.Property<int>("StationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("BikesAtStation");
                });

            modelBuilder.Entity("BikeRental.StationService.Domain.Entities.External.Bike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ExternalBikes");
                });

            modelBuilder.Entity("BikeRental.StationService.Domain.Entities.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("BikeRental.StationService.Domain.Entities.BikeAtStation", b =>
                {
                    b.HasOne("BikeRental.StationService.Domain.Entities.Station", "Station")
                        .WithMany("BikesAtStation")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("BikeRental.StationService.Domain.Entities.Station", b =>
                {
                    b.Navigation("BikesAtStation");
                });
#pragma warning restore 612, 618
        }
    }
}
