@BikeRental.StationService_HostAddress = http://localhost:5139

POST {{BikeRental.BikeService_HostAddress}}/station/
Accept: application/json
Content-Type: application/json
{
  "code": "ST001",
  "location": "Lodz, Piotrkowska 100",
  "capacity": 30
}

###
GET {{BikeRental.BikeService_HostAddress}}/station/
Accept: application/json