@BikeRental.StationService_HostAddress = http://localhost:5139

POST {{BikeRental.StationService_HostAddress}}/station/
Accept: application/json
Content-Type: application/json
{
  "code": "ST001",
  "location": "Lodz, Piotrkowska 100",
  "capacity": 30
}

###
GET {{BikeRental.StationService_HostAddress}}/station/
Accept: application/json

###
POST {{BikeRental.StationService_HostAddress}}/station/1/bike
Accept: application/json
Content-Type: application/json
{
  "externalBikeId": "052DD06B-A15F-4F41-9F8C-7A99ECECEC37"
}

###
DELETE {{BikeRental.StationService_HostAddress}}/station/1/bike
Accept: application/json
Content-Type: application/json
{
  "externalBikeId": "052DD06B-A15F-4F41-9F8C-7A99ECECEC36"
}
