@BikeRental.BikeService_HostAddress = http://localhost:5146

POST {{BikeRental.BikeService_HostAddress}}/bike/
Accept: application/json
Content-Type: application/json
{
  "model": "Trek FX 3 Disc12",
  "color": "Blac2k",
  "lastServiceDate": "2024-08-09"
}

###
GET {{BikeRental.BikeService_HostAddress}}/bike/
Accept: application/json