// <auto-generated />
using System;
using BikeRental.BikeService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BikeRental.BikeService.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250914082832_RenameBikeAtStation")]
    partial class RenameBikeAtStation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("BikeRental.BikeService.Domain.Entities.Bike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("LastServiceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Bikes");
                });

            modelBuilder.Entity("BikeRental.BikeService.Domain.Entities.External.BikeAtStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BikeId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StationExternalId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BikeId");

                    b.ToTable("ExternalBikeAtStations");
                });

            modelBuilder.Entity("BikeRental.BikeService.Domain.Entities.External.BikeAtStation", b =>
                {
                    b.HasOne("BikeRental.BikeService.Domain.Entities.Bike", "Bike")
                        .WithMany()
                        .HasForeignKey("BikeId");

                    b.Navigation("Bike");
                });
#pragma warning restore 612, 618
        }
    }
}
