// <auto-generated />
using System;
using BikeRental.BikeService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BikeRental.BikeService.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260104155914_AddStationProp")]
    partial class AddStationProp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("BikeRental.BikeService.Domain.Entities.Bike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BikeAtStationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("LastServiceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BikeAtStationId")
                        .IsUnique();

                    b.ToTable("Bikes");
                });

            modelBuilder.Entity("BikeRental.BikeService.Domain.Entities.BikeAtStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BikeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("ExternalBikeAtStations");
                });

            modelBuilder.Entity("BikeRental.BikeService.Domain.Entities.External.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("BikeRental.BikeService.Domain.Entities.Bike", b =>
                {
                    b.HasOne("BikeRental.BikeService.Domain.Entities.BikeAtStation", "BikeAtStation")
                        .WithOne("Bike")
                        .HasForeignKey("BikeRental.BikeService.Domain.Entities.Bike", "BikeAtStationId");

                    b.Navigation("BikeAtStation");
                });

            modelBuilder.Entity("BikeRental.BikeService.Domain.Entities.BikeAtStation", b =>
                {
                    b.HasOne("BikeRental.BikeService.Domain.Entities.External.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("BikeRental.BikeService.Domain.Entities.BikeAtStation", b =>
                {
                    b.Navigation("Bike");
                });
#pragma warning restore 612, 618
        }
    }
}
